### servicecomb config ###
servicecomb-config-order: 1
APPLICATION_ID: edgegallery
service_description:
  name: mec-appstore
  version: 1.0.0
  environment: development
servicecomb:
  service:
    registry:
      address: ${SC_ADDRESS}
  rest:
    address: ${LISTEN_IP:}:8099
    servlet:
      urlPattern: /cse/*
  uploads:
    directory: /home/appstore
    maxSize: -1

### spring config ###
server:
  port: 8099
  ssl:
    enabled: ${SSL_ENABLED:false}
    protocol: TLS
    enabled-protocols: [TLSv1.2]
    ciphers: [TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,
              TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384]
    key-store: ${SSL_KEY_STORE_PATH:}
    key-store-password: ${SSL_KEY_STORE_PASSWORD:}
    key-store-type: ${SSL_KEY_STORE_TYPE:}
    key-alias: ${SSL_KEY_ALIAS:}
spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_IP:appstore-be-postgres-svc}:${POSTGRES_PORT:5432}/${POSTGRES_DB_NAME:appstoredb}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    schema: classpath:appstore-be.sql
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 5120MB
      max-request-size: 5120MB
security:
  oauth2:
    resource:
      jwt:
        key-uri: ${AUTH_SERVER_ADDRESS:http://user-mgmt-svc:8067}/oauth/token_key
## mybatis config ##
mybatis:
  mapper-locations: classpath:mybatis/sql/*.xml

### appstore-be config ###
appstore-be:
  temp-path: /usr/app/temp
  package-path: /usr/app/packages
  appstore-repo-password: ${APPSTORE_REPO_PASSWORD:}
  appstore-repo-username: ${APPSTORE_REPO_USERNAME:}
  appstore-repo-endpoint: ${APPSTORE_REPO_ENDPOINT:}
  dev-repo-password: ${DEV_REPO_PASSWORD:}
  dev-repo-username: ${DEV_REPO_USERNAME:}
### atp config ###
atp:
  urls:
    create-task: https://atp-svc:8073/edgegallery/atp/v1/tasks
    query-task: https://atp-svc:8073/edgegallery/atp/v1/tasks/%s

### poke feature config ###
poke:
  platformName: ${PLATFORM_NAME:EdgeGallery AppStore}
  host-url: ${PLATFORM_URL:http://127.0.0.1:8099}
  atp-report-url: ${ATP_REPORT_URL:http://127.0.0.1:8073/atpreport?taskId=%s}

